version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: percyjackson
    ports:
      - "5432:5432" 

volumes:
  postgres:
